name: Linux
on: [push]
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    strategy:
      matrix:
        compiler: ["gcc", "clang"]
    name: build (${{ matrix.compiler }})
    steps:

      - name: Setup Environment (compiler=${{ matrix.compiler }})
        run: |
          sudo apt-get install tcl8.6-dev cmake
          mkdir "$HOME/install dir"
          echo "CFGOPT_COMMON=--with-tcl=/usr/lib/tcl8.6" >> $GITHUB_ENV
          echo "CC=$COMPILER" >> $GITHUB_ENV
        env:
          COMPILER: ${{ matrix.compiler }}
          OPTS: ${{ matrix.compiler }}

      - name: Checkout cJSON
        uses: actions/checkout@v4
        with:
          repository: DaveGamble/cJSON
          ref: v1.7.18
          path: cjson
      - name: Configure cJSON
        working-directory: cjson
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/root -DCMAKE_PREFIX_PATH=$HOME/root
      - name: Build cJSON
        working-directory: cjson/build
        run: |
          make -j || {
            echo "::error::Failure during Build cJSON"
            exit 1
          }
      - name: Install cJSON
        working-directory: cjson/build
        run: |
          make install || {
            echo "::error::Failure during Install cJSON"
            exit 1
          }

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/root -DCMAKE_PREFIX_PATH=$HOME/root -DTCL_INCLUDE_DIR=/usr/include/tcl8.6 -DTCL_LIBRARY_DIR=/usr/lib/x86_64-linux-gnu
      - name: Build
        working-directory: build
        run: |
          make -j || {
            echo "::error::Failure during Build"
            exit 1
          }
      - name: Run Tests
        working-directory: build
        run: |
          LD_LIBRARY_PATH="$HOME/root/lib" make test || {
            echo "::error::Failure during Test"
            exit 1
          }
      - name: Test-Drive Installation
        working-directory: build
        run: |
          make install || {
            echo "::error::Failure during Install"
            exit 1
          }
